/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-07-31 06:45:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pro;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("	<!-- 같이 출력하기 위해 include를 사용함 -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "insert.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"row my-5\">\r\n");
      out.write("	<div class=\"col\">\r\n");
      out.write("		<h1 class=\"text-center\">상품목록</h1>\r\n");
      out.write("		<div class=\"row mb-3\">\r\n");
      out.write("			<form name=\"frm\" class=\"col-6 col-md-4\">\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("					<input name=\"query\" placeholder=\"검색\" class=\"form-control\">\r\n");
      out.write("					<button class=\"btn btn-primary\">검색</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("			<div class=\"col pt-2\">\r\n");
      out.write("				<span>검색수</span>\r\n");
      out.write("				<span id=\"total\">100</span>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"div_product\"></div>\r\n");
      out.write("		<div id=\"pagination\" class=\"pagination justify-content-center\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 상품목록 템플릿 -->\r\n");
      out.write("<script id=\"temp_product\" type=\"text/x-handlebars-template\">\r\n");
      out.write("	<table class=\"table\">\r\n");
      out.write("		{{#each .}}\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td class=\"code\">{{code}}</td>\r\n");
      out.write("			<td><input value=\"{{name}}\" class=\"name\"></td>\r\n");
      out.write("			<td class=\"text-end pe-5\">\r\n");
      out.write("				<input value=\"{{price}}\" class=\"price\">\r\n");
      out.write("				<br>\r\n");
      out.write("				<span class=\"fprice\">{{fprice}}</sapn>\r\n");
      out.write("				{{fprice}}\r\n");
      out.write("			</td>\r\n");
      out.write("			<td>{{fdate}}</td>\r\n");
      out.write("			<td><button class=\"btn btn-danger btn-sm\" code=\"{{code}}\">삭제</td>\r\n");
      out.write("			<td><button class=\"btn btn-success btn-sm\" >수정</button></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		{{/each}}\r\n");
      out.write("	</table>\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("	\r\n");
      out.write("	let query=\"\";\r\n");
      out.write("	//수정버튼을 클릭한 경우\r\n");
      out.write("	$(\"#div_product\").on(\"click\", \".btn-success\", function(){\r\n");
      out.write("		const row=$(this).parent().parent();\r\n");
      out.write("		const code=row.find(\".code\").html();\r\n");
      out.write("		const name=row.find(\".name\").val();\r\n");
      out.write("		const price=row.find(\".price\").val();\r\n");
      out.write("		if(confirm(\"상품정보를 수정하실래요?\")){\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type\"post\",\r\n");
      out.write("				url:\"/pro/update\",\r\n");
      out.write("				data:{code:code, name:name, price:price},\r\n");
      out.write("				success:function(){\r\n");
      out.write("					alert(\"수정완료\");\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	//삭제버튼을 클릭한 경우\r\n");
      out.write("	$(\"#div_product\").on(\"click\", \".btn-danger\", function(){\r\n");
      out.write("		const code=$(this).attr(\"code\");\r\n");
      out.write("		const name=$(this).parent().parent().find(\".name\").text();\r\n");
      out.write("		if(confirm(name +\"상품을 삭제하실래요?\")){\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type:\"post\",\r\n");
      out.write("				url:\"/pro/delete\",\r\n");
      out.write("				data:{\"code\":code},\r\n");
      out.write("				success:function(){\r\n");
      out.write("					alert(\"삭제완료\")\r\n");
      out.write("					getTotal();\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$(frm).on(\"submit\", function(e){\r\n");
      out.write("		e.preventDefault();\r\n");
      out.write("		query=$(frm.query).val();\r\n");
      out.write("		getList(1);\r\n");
      out.write("		getTotal();\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	function getList(page){\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type:\"get\",\r\n");
      out.write("			url:\"/pro/list.json\",\r\n");
      out.write("			data:{page:page, query:query},\r\n");
      out.write("			dataType:\"json\",\r\n");
      out.write("			success:function(data){\r\n");
      out.write("				console.log(data);\r\n");
      out.write("				const temp=Handlebars.compile($(\"#temp_product\").html());\r\n");
      out.write("				const html=temp(data);\r\n");
      out.write("				$(\"#div_product\").html(html);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	$('#pagination').twbsPagination({\r\n");
      out.write("	    totalPages:1,	// 총 페이지 번호 수\r\n");
      out.write("	    visiblePages: 5,	// 하단에서 한번에 보여지는 페이지 번호 수\r\n");
      out.write("	    startPage : 1, // 시작시 표시되는 현재 페이지\r\n");
      out.write("	    initiateStartPageClick: false,	// 플러그인이 시작시 페이지 버튼 클릭 여부 (default : true)\r\n");
      out.write("	    first : '<i class=\"bi bi-chevron-double-left\"></i>',	// 페이지네이션 버튼중 처음으로 돌아가는 버튼에 쓰여 있는 텍스트\r\n");
      out.write("	    prev : '<i class=\"bi bi-caret-left-fill\"></i>',	// 이전 페이지 버튼에 쓰여있는 텍스트\r\n");
      out.write("	    next : '<i class=\"bi bi-caret-right-fill\"></i>',	// 다음 페이지 버튼에 쓰여있는 텍스트\r\n");
      out.write("	    last : '<i class=\"bi bi-chevron-double-right\"></i>',	// 페이지네이션 버튼중 마지막으로 가는 버튼에 쓰여있는 텍스트\r\n");
      out.write("	    onPageClick: function (event, page) {\r\n");
      out.write("	    	getList(page);\r\n");
      out.write("	    }\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	getTotal();\r\n");
      out.write("	function getTotal() {\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type:\"get\",\r\n");
      out.write("			url:\"/pro/total\",\r\n");
      out.write("			data:{query:query},\r\n");
      out.write("			success:function(data){\r\n");
      out.write("				const totalPages=Math.ceil(data/5);\r\n");
      out.write("				$(\"#total\").html(data);\r\n");
      out.write("				if(totalPages==0){\r\n");
      out.write("					alert(\"검색한 결과가 없습니다.\")\r\n");
      out.write("					$(frm.query).val(\"\");\r\n");
      out.write("					$(\"#pagination\").hide();\r\n");
      out.write("				}else{\r\n");
      out.write("					$(\"#pagination\").show();\r\n");
      out.write("					$(\"#pagination\").twbsPagination(\"changeTotalPages\", totalPages, 1);\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	}\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
